# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # [push]
  push:
    branches: [feature/cicd]

#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: npm install and build webpack
#         run: |
#           cd mlopsapi
#           npm install --save --legacy-peer-deps
#           npm run build
#       - uses: actions/upload-artifact@main
#         with:
#           name: webpack artifacts
#           path: public/
#   test:
#     needs: build
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-2016]
#         node-version: [12.x, 14.x]
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/download-artifact@main
#         with:
#           name: webpack artifacts
#           path: public
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm install, and test
#         run: |
#           npm install
#           npm test
#         env:
#           CI: true
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        run: |
          cd api/api-nest/mlopsapi
          npm install --save --legacy-peer-deps
          npm run build --if-present
          npm test
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"

      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
